#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Pilberry runs a car radio based on Raspberry Pi
# Copyright 2014 Olivier Cecillon <ocecillon@users.sourceforge.net>
# and Nicolas Hainaux <nico_h@users.sourceforge.net>

# This file is part of Pilberry.

# Pilberry is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# any later version.

# Pilberry is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Pilberry; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

# This script listens to the keypad

# Python packages|modules imports
import time
import logging
import logging.config

# Adafruit packages|modules imports
from lib.hardware_drivers.Adafruit_CharLCDPlate import Adafruit_CharLCDPlate

# Pilberry packages|modules imports
from lib.hardware_drivers.key_handler import KeyHandler
from lib.globals import LOG_DIR

logging.config.fileConfig(LOG_DIR + 'logging.conf')

KEYPAD = Adafruit_CharLCDPlate()
KEYPAD.clear()
KEYPAD.message("")

SELECT = KEYPAD.SELECT
RIGHT = KEYPAD.RIGHT
DOWN = KEYPAD.DOWN
UP = KEYPAD.UP
LEFT = KEYPAD.LEFT

KEY_IDS = [SELECT, RIGHT, LEFT, UP, DOWN]

KEYPAD_HANDLERS = {SELECT : KeyHandler('SELECT'),
                   RIGHT : KeyHandler('RIGHT'),
                   LEFT : KeyHandler('LEFT'),
                   UP : KeyHandler('UP'),
                   DOWN : KeyHandler('DOWN'),
                  }


while True:
    for k in KEY_IDS:
        KEYPAD_HANDLERS[k].handle(KEYPAD.buttonPressed(k))

    time.sleep(0.02)

