#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Pilberry runs a car radio based on Raspberry Pi
# Copyright 2014 Olivier Cecillon <ocecillon@users.sourceforge.net>
# and Nicolas Hainaux <nico_h@users.sourceforge.net>

# This file is part of Pilberry.

# Pilberry is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# any later version.

# Pilberry is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Pilberry; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

# This script is run by cmus to give status informations

# Python packages|modules imports
import sys
import logging

# Pilberry packages|modules imports
from lib.carrier.Carrier import Carrier

logging.basicConfig(filename='./log/audio_feedback.log',
                    level=logging.DEBUG,
                    format='%(asctime)s %(filename)s: %(funcName)s: %(message)s',
                    datefmt='%Y/%m/%d %H:%M:%S')

logging.debug('---------------------------------'\
              + '--------------------------------------------------')

with Carrier() as C:
    # Taken from
    # https://github.com/freshprince/cmuscrobbler/blob/master/cmuscrobbler.py
    data = {}

    for k, v in zip(sys.argv[1::2], sys.argv[2::2]):
        logging.debug('retrieved:     ' + str(k) + ' : ' + str(v))
        data[k] = v

    # data will be a hash like this:
    """
    {'album': 'Basics',
    'artist': 'Funny van Dannen',
    'duration': '147',
    'file': '/home/david/m/m/+DB/Funny_van_Dannen/Basics/01-Guten_Abend.mp3',
    'status': 'stopped',
    'title': 'Guten Abend',
    'tracknumber': '1'}
    """

    for field in ['artist', 'title', 'album',
                  'tracknumber', 'status', 'file']:
        if not field in data:
            data[field] = ""

    logging.debug('cmus sent feedback: ' + str(data))

    # Notification to pilberry_modes
    notification = {'status' : data['status'],
                    'full_path' : data['file']
                   }

    logging.debug('sending notification: ' + str(notification))

    C.send('TEST_MBP2', notification)
