#!/usr/bin/env sh

### BEGIN INIT INFO
# Provides: lcd_bootup_message
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Liquid Crystal Display
### END INIT INFO


export HOME
case "$1" in
    start)
        /home/pi/pilberry/bin/lcd_bootup_message  2>&1 &
    ;;
    stop)

    ;;
    *)
        echo "Usage: /etc/init.d/lcd {start|stop}"
        exit 1
    ;;
esac
exit 0
