#!/usr/bin/env sh

### BEGIN INIT INFO

# Provides:          pilberry
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start pilberry

### END INIT INFO

export LANG=fr_FR.UTF-8
export LANGUAGE=fr_FR.UTF-8
export LC_NUMERIC=fr_FR.UTF-8
export LC_MESSAGES=fr_FR.UTF-8

case "$1" in

    start)
        echo "Starting pilberry"
        /home/pi/pilberry/bin/start 1> /home/pi/pilberry/log/start_err.log 2>&1
        ;;

    stop)
        echo "Stopping pilberry"
        /home/pi/pilberry/bin/stop
        ;;

    reload|restart)
        "$0" stop
        "$0" start
        ;;

    *)
        echo "Usage: $0 start|stop|restart|reload"
        exit 1

esac

exit 0
