#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Pilberry runs a car radio based on Raspberry Pi
# Copyright 2014 Olivier Cecillon <ocecillon@users.sourceforge.net>
# and Nicolas Hainaux <nico_h@users.sourceforge.net>

# This file is part of Pilberry.

# Pilberry is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# any later version.

# Pilberry is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Pilberry; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

# This script listens to the keypad

# Python packages|modules imports
import time
import datetime
import RPi.GPIO as GPIO
import logging
import logging.config

# Pilberry packages|modules imports
from lib.hardware_drivers.key_handler import KeyHandler
from lib.globals import LOG_DIR

logging.config.fileConfig(LOG_DIR + 'logging.conf')

GPIO.setmode(GPIO.BCM)
GPIO.setup(22, GPIO.IN)

k = KeyHandler('SELECT')

def is_pressed(n):
    return GPIO.input(n) == False

last = is_pressed(22)

print("ready")

while True:
    #if is_pressed(22) != last:
    #    print(str(datetime.datetime.now()) + " >> is pressed: " + str(not last))
    #    last = not last

    k.handle(is_pressed(22))

    time.sleep(0.02)





