#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Pilberry runs a car radio based on Raspberry Pi
# Copyright 2014 Olivier Cecillon <ocecillon@users.sourceforge.net>
# and Nicolas Hainaux <nico_h@users.sourceforge.net>

# This file is part of Pilberry.

# Pilberry is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# any later version.

# Pilberry is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Pilberry; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

# Simple server script that waits for command, to test browsing a file system

# Python packages|modules imports
import time
import pickle
import configparser
import socket
import sys, os
import argparse
import RPIO
import logging

# Pilberry packages|modules imports
from lib.globals import SOCKETS_CONFIG, cmd_match_list
from lib.tree.Tree import Tree
import lib.globals as globals

logging.basicConfig(filename='../log/tree_browser.log',
                    filemode='w',
                    level=logging.DEBUG,
                    format='%(asctime)s %(filename)s: %(funcName)s: %(message)s',
                    datefmt='%Y/%m/%d %H:%M:%S')

# Get the socket file name from sockets' conf file
SOCKETS_PORTS = [int(SOCKETS_CONFIG['TREE_BROWSER']['PORT']),
                 int(SOCKETS_CONFIG['TREE_BROWSER2']['PORT'])
                 ]

parser = argparse.ArgumentParser(description='Script to test driving a tree')
parser.add_argument('root', metavar='ROOT_PATH', type=str, nargs='+',
                   help='the "adress" of the destination process')

tree_root = vars(parser.parse_args())['root'][0]

if not os.path.isdir(tree_root):
    print(tree_root + " is not a valid directory. Exiting")
    sys.exit()

globals.current_tree = Tree(root=tree_root)
t = globals.current_tree

def report():
    print("xnode is in: " + t.xnode.parent['full_path'])
    print("xnode is " \
          + t.xnode['file_name']\
          + " and has " \
          + str(len(t.xnode.children)) \
          + " children.")
    print("head is \033[32m" \
          + t.head['file_name']\
          + "\033[0m and has " \
          + str(len(t.head.children)) \
          + " children.")
    print("global.exploring: " + str(globals.exploring) \
          + "          global.cmus_status: "+ str(globals.cmus_status))
    result = ""
    for i in range(len(t.xnode.neighbours)):
        open_bracket = "["
        close_bracket = "]"
        if t.xnode.neighbours[i]['file_name'] == t.xnode['file_name']:
            open_bracket = "\033[33m<<"
            close_bracket = ">>\033[0m"

        result += open_bracket \
               + t.xnode.neighbours[i]['file_name'] \
               + close_bracket \
               + " "

    result += "\nWaiting for next command..."

    print(result)


report()

def cmd_callback(socket, data):
    raw_cmd = pickle.loads(data)
    if raw_cmd == 'QUIT':
        print("Shutting down server")
        sys.exit()
    else:
        try:
            cmd = cmd_match_list[raw_cmd]
        except KeyError:
            print("Received: " + raw_cmd + ". Unknown command, no action")

        else:
            print("Received: " + cmd)
            t.handle(cmd)

            report()


def cmus_callback(socket, data):
    notification = pickle.loads(data)
    if notification['status'] in globals.CMUS_NOTIFICATIONS:
        print("Received status notification: " + notification['status'])
        globals.cmus_status = notification['status']
        if 'playing' == globals.cmus_status:
            if t.head['full_path'] != notification['full_path']:
            #___
                logging.debug("noticed that head doesn't match current song")
                # Current song doesn't match head node
                # Let's try to find the node matching current song
                # First, check if it's one of the song of the same 'directory'
                found = False
                for n in t.head.neighbours:
                    if n['full_path'] == notification['full_path']:
                        t.set_head(n)
                        found = True
                if found:
                    logging.debug("found the node matching current song")
                    print("Updated head Node, waiting for next command...\n")
                ##
                #   @todo   If the next node at right is not the good one, then
                #           look for the good one! In the best case, a data-
                #           base is available and we can find it thanks to its
                #           full path. If no database is available, then a
                #           search algorithm has to be found...


    else:
        print("Received UNKNOWN status notification: " + notification['status'])

    print("On full path: " + notification['full_path'])

    report()


RPIO.add_tcp_callback(SOCKETS_PORTS[0], cmd_callback)
RPIO.add_tcp_callback(SOCKETS_PORTS[1], cmus_callback)

# Blocking main epoll loop
RPIO.wait_for_interrupts()

