#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Pilberry runs a car radio based on Raspberry Pi
# Copyright 2014 Olivier Cecillon <ocecillon@users.sourceforge.net>
# and Nicolas Hainaux <nico_h@users.sourceforge.net>

# This file is part of Pilberry.

# Pilberry is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# any later version.

# Pilberry is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Pilberry; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

# Python packages|modules imports
import time
import pickle
import configparser
import socket
#import RPIO

# Pilberry packages|modules imports
from lib.globals import SOCKETS_CONFIG, cmd_match_list

# Get the socket file name from sockets' conf file
SOCKET_FILE = str(SOCKETS_CONFIG['TEST_TREE_BROWSER']['FILE'])

print("Socket file: " + SOCKET_FILE)

server = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
server.bind(SOCKET_FILE)

print("Waiting for instructions...")
while True:
    raw_cmd = pickle.loads(server.recv(1024))
    if raw_cmd == 'QUIT':
        print("Shutting down server")
        sys.exit()
    else:
        cmd = cmd_match_list[raw_cmd]
        print(cmd)
